### ISSUE TITLE
No playback progress slider in notification [Android]

### ISSUE THREAD

**Issue by betsythefc** [podverse/podverse-rn#1027]
**Describe the bug**
There is no progress bar or time index in the playing notification

**To Reproduce**
1. Play a podcast, check notification

**Expected behavior**
- A slider/progress bar showing how long you've listened, and how much longer you have.
- A time index of where I am in the podcast

**Screenshots**
![2022-04-15 Podverse, No Play Status](https://user-images.githubusercontent.com/15450365/165142864-c9db9890-4edf-4fe7-8996-335fd127648b.jpg)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy Z Flip 3 5G
 - OS: Android 12
 - App Version 4.3.5 F-Droid

**Additional context**
This may also be impacting bluetooth -- when connected to bluetooth there is no time index on my cars screen. This is only missing on Podverse. When I used AntennaPod, it worked.

**Comment by mitchdowney** [comment]
Ahh, looks like this was off my radar because my Pixel 4a doesn't seem to show a progress bar for any apps.

Spotify:
![image](https://user-images.githubusercontent.com/2262919/165351233-f5d8f96d-e115-48ed-97a4-1cc0c11a652f.png)

Podverse:
![image](https://user-images.githubusercontent.com/2262919/165351257-f1b5ef1b-646f-4733-a9c1-b31df459c289.png)

Unless there is some sort of phone setting I need to enable, it looks like my phone doesn't show the issue.

In any case, I'm going to look into upgrading our react-native-track-player to a newer version, and see if that fixes the issue.

Thanks as always for these helpful bug reports 🙏

**Comment by mitchdowney** [comment]
I think we fixed it:

![image](https://user-images.githubusercontent.com/2262919/165380355-579e4f2e-3739-4b95-9d59-10adeed15dd0.png)

Basically, we create a track with metadata information before we load it in the react-native-track-player. However, we weren't setting a duration in the metadata. That's because we don't always know the duration of the track until it is loaded in the player...so I added logic that updates the metadata with the duration after the track is loaded and ready.

The fix should be in our next release v4.4.2.

https://github.com/podverse/podverse-rn/pull/1029

**Comment by betsythefc** [comment]
That is fantastic. I'll let you know how it works on my end, and maybe this metadata will fix the display of track progression on my cars bluetooth! Thank you so much!

**Comment by betsythefc** [comment]
I'm confirming that the progress bar works on my phone, and also works on my car via bluetooth!
![2022-05-02 Podverse, Play Notification, Expanded](https://user-images.githubusercontent.com/15450365/166605825-35c9cbc1-0869-4304-a06f-551374b9e306.jpg)
