### ISSUE TITLE
Filter/search subscribed podcasts 

### ISSUE THREAD

**Issue by Ramblurr** [podverse/podverse-rn#1097]
**Is your feature request related to a problem? Please describe.**

I have a lot of podcast subscriptions. Finding the podcast I'm looking for in my list is very difficult. The search bar at the top searches the entire podcast index which isn't helpful.

I filter my own podcast subscriptions multiple times per day, but only search for new podcasts once a month or less.

**Describe the solution you'd like**
I'd love to see an option to filter my subscriptions. It could search the podcast title and description fields.

**Describe alternatives you've considered**

I switched from Pocket casts, and I have to say I didn't filter (via typing) for my podcasts very often. I think that's because their subscriptions list is a tightly packed tiled layout of podcast covers.

I just checked on my Samsung S21 phone, in pocketcasts I can see 24 of my subscriptions at once. In podverse I see only 7.

**Additional context**
![Screenshot_20220709-123349_Pocket Casts](https://user-images.githubusercontent.com/14830/178102232-d8549c99-cdef-44b3-bab6-7a04793219de.jpg)
![Screenshot_20220709-123403_Podverse](https://user-images.githubusercontent.com/14830/178102233-8118cbec-7839-46cc-9a27-a685e904e732.jpg)

**Comment by Chris869218** [comment]
Second this. The search bar up top makes it seem like it’s going to search subscribed podcasts. If it did that, showing only 7 would be fine.

**Comment by mitchdowney** [comment]
@Ramblurr @Chris869218 thanks for the ideas. We do have plans to add an optional grid view, so I think we can get to this in the next month or two.

The subscribed filter is a good point too. It's a challenge with our design to not put too many buttons on the screen. We'll think about how to add this though.

**Comment by Chris869218** [comment]
It seems it wouldn’t take up any additional real estate if the search bar on the episodes screen or podcasts screen just followed the current filter. If you were on “all podcasts” the expected behavior would be the search bar would search all podcasts. If you were on “subscribed” the expected behavior would be a search within the subscribed podcasts. That’s not to say the change would be easy, but screen real estate shouldn’t change. Thanks!

**Comment by Ramblurr** [comment]
Thanks for taking this under consideration.

Another idea, to not clutter the interface with more buttons would be to have the search bar sort subscribed podcasts to the top. However it would be important to me that this "search" is super fast. I'd rather not have to wait for search  replies from the server in order to filter a list of my own local podcasts.

**Comment by mitchdowney** [comment]
@Chris869218 the problem with making "Search Subscribed" filter subscribed instead of search

@Ramblurr clever idea about combining filter + "search from server" into the input. It sounds doable and would be an improvement...

@kreonjr and I discussed this recently. Still not sure which direction we want to go (might return a full-fledged Search screen into the UX), but we hope to make a decision soon.

Also, re: grid view, @kreonjr has already finished most of the work...BUT while working on this, we realized a long-standing bug we have had with images not loading in offline mode would completely break the grid-view experience 😕 we use a library called react-native-fast-image which supposedly has caching, but it seems like it has never worked properly for offline usage. It appears we are going to need to write our own custom component for storing images to disk and loading them. It seems like our grid view release will be blocked until we fix this storage/caching problem.

**Comment by mitchdowney** [comment]
@Chris869218 @Ramblurr @kreonjr alright...I added something intended to help with this, but I kind of just jammed it into the existing PodcastsScreen UX 😑 #1228

I think if we were to _properly_ address this feature, we may need to add an actual Search screen. Then the "filter" bars could just be for filtering subscribed podcasts, and to search our server-side directory, there would be a Search screen you could use. Adding a search icon though might be difficult in our already pretty busy UI...

Hopefully this is at least an improvement for now though.

![CleanShot 2022-09-17 at 21 09 00](https://user-images.githubusercontent.com/2262919/190882701-6eedb886-f826-4273-bcfa-05d5c6ffda84.gif)

**Comment by Ramblurr** [comment]
>  think if we were to properly address this feature, we may need to add an actual Search screen. Then the \"filter\" bars could just be for filtering subscribed podcasts, and to search our server-side directory, there would be a Search screen you could use. Adding a search icon though might be difficult in our already pretty busy UI...

This looks like a good workaround for now, thanks!

I think having a separate search/discover screen from the list of subscribed podcasts makes a lot of sense. 

Those are backed by two distinct actions: exploring or searching for new content vs trying to find something i already know I have.

By the way the cover view is real nice :) I noticed one bug when you have bad connectivity, the cover art is only partially shown because it hasn't finished downloading. But I guess that belongs in another ticket..
