### ISSUE TITLE
Persistent unplayed episode badges

### ISSUE THREAD

**Issue by freekvh** [podverse/podverse-rn#1239]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when the unlistened episode counting badge disappears when I open a feed but there are still unlistened podcast episode in there

**Describe the solution you'd like**
I would like to always see a badge with the unplayed episode regardless of whether I took a peak inside a feed.

**Comment by mitchdowney** [comment]
@freekvh good idea. I'm not sure yet how we make it work in the UX though. What if you haven't listened to an episode, and it turns out you don't want to ever listen to the episode? Does it hang around in the UI as unplayed forever? Do we need a new interaction for dismissing the notification for "new episode found"? We already have a "Mark as Played" feature, but this would need to be separate from "Mark as Played" as just because you dismiss a "new episode found" notification, that doesn't mean you want it saved in your history as "I have already listened to this episode until the end".

Anyway, there's a bit of work involved in figuring out how exactly to do this.

Sorry this is not what you're looking for, but as a workaround for this you could add items you will want to play later to your Queue. That way you don't lose the reference to the new episode.

**Comment by mitchdowney** [comment]
@freekvh I'll try to update this to behave like follows...instead of hiding all the notifications when you open the podcast's page, we hide the badge if the user presses play on the episode, OR the user navigates to that episode's episode screen.

This isn't a perfect UX since "viewing" the episode's screen isn't the same as "playing" the episode...but we need to provide at least some way for users to dismiss the notification without having to play the episode. Rather than put another button in our busy UI, we're going to try going with playing or visiting the episode screen to dismiss the notification.

**Comment by mitchdowney** [comment]
@freekvh alright, here's what the new implementation looks like:

![CleanShot 2022-09-22 at 20 39 02](https://user-images.githubusercontent.com/2262919/191878518-adac6048-4430-4a9b-b49e-21d0cc4e9ca7.gif)

This should be in v4.6.7-prod.2 #1255

**Comment by freekvh** [comment]
Wow that is a fast reply, and fix, thank you!

I think for me most intuitive would be if the badge would really indicate the unplayed episodes, dismissing them is by playing episode or by marking episode as played. This may lead to huge number in the badge so perhaps the badge could reflect downloaded unplayed episodes? If auto delete is at max 5 most recent episodes for example, then the counter never goes over 5.

But I still like what you made now, I solves my issue, thank you.

Btw the badges are (to me) really important  because they signal what fresh content I can listen to when I open the app, so if you ask me they can be bright red :)

**Comment by mitchdowney** [comment]
@freekvh @kreonjr ok, instead of dismissing the indicator when you visit the EpisodeScreen, I just updated it to dismiss either 1) when you play, or 2) when you press the "Clear new episode indicators" button. #1256 

![CleanShot 2022-09-23 at 07 29 38](https://user-images.githubusercontent.com/2262919/191960868-45501770-a97d-4a75-9b35-4247e7852425.gif)

As for the color choice...I might reserve that decision for our UX designer friend after the next UX audit they do. I'm trying not to introduce too many different colors into the UI, but I don't maybe red would be the better choice here 🤷 

Hope that's an improvement at least!
