### ISSUE TITLE
Show account info under More > Settings > Account

### ISSUE THREAD

**Issue by freekvh** [podverse/podverse-rn#1242]
**Is your feature request related to a problem? Please describe.**
Checking Settings => Account only shows  a big button: "Delete account"

**Describe the solution you'd like**
I guess this button means I have an account? Or do I? It was a while ago I set this up. What are the details? At minimum I would expect my email address there, perhaps some other things I shared upon account creation?

**Comment by mitchdowney** [comment]
@freekvh good idea. We can add more user info to this screen.

**Comment by mitchdowney** [comment]
@freekvh just added more info the Settings > Account screen.

The edit buttons are a bit awkward because they redirect to the "Edit Profile" screen (which you can get to by My Library > My Profile > Edit Profile)...but hopefully this is at least an improvement.

![CleanShot 2022-09-21 at 21 21 59](https://user-images.githubusercontent.com/2262919/191644860-8127030d-ce78-475f-8afa-c2c7be6e178f.gif)

**Comment by mitchdowney** [comment]
This should be in the v4.6.7-prod.2 release.

**Comment by freekvh** [comment]
This is absolutely great and makes this screen less confusing, thank you!
