### ISSUE TITLE
Playing episode stream on car Bluetooth jumps back

### ISSUE THREAD

**Issue by EricKerby** [podverse/podverse-rn#1350]
Apologies this is hard to describe but continues to happen frequently.
Using a Pixel 5 connected to Bluetooth of a Tesla Model 3, when playing a podcast episode stream (not a downloaded episode), very often the playback will jump backwards a chuck of seconds or couple minutes. I can jump forward to get back to the same position, but then the episode playback will end early as if the stream was truncated.

As an example, I find this happens often when playing episodes of the Bobby Bones Show podcast. If I have downloaded an episode, the random jump/skip doesn't happen.

**Comment by mitchdowney** [comment]
@EricKerby thanks for reporting this. I've been having this randomly with some podcasts for the past few months while streaming...and I'm wondering if is related to dynamically inserted ads. I'm thinking at some point during the stream, a different version of the audio file gets returned, and the audio jumps to a different position. "The Bobby Bones Show" is on iHeart radio and I wouldn't be surprised if they have dynamic ads.

I'm not totally sure about that is it though, because it seems like the app almost always jumps *backward* for me. That said if a episode jumps forward I might be less likely to notice it.

We have major changes to our audio player in the hopefully near future #1179 so we're probably going to hold off on trying to fix this until after that. One thing we could possibly do is cache the stream of the currently playing podcast, so that the app can stop making network requests for the stream. Or maybe (hopefully) when we upgrade the audio library the problem will go away.

In any case, sorry for the annoying bug. If you ever notice any other patterns with it or exceptions to my "dynamic ads" theory I'd appreciate the info.

**Comment by mitchdowney** [comment]
At this time, the only theory I still have is problems with streaming episodes that use dynamic ads. While we want to fix everything, it's difficult to say how deep I want to go trying to fix an issue that the content creator basically creates by broadcasting a stream that can change to a new stream every X minutes or so.

I'm going to mark this as "won't fix" for now, since we can recommend people who run into the issue download episodes of shows that have dynamic ads instead of streaming as a workaround. We can reopen the issue based on popular demand.
