### ISSUE TITLE
Enable auto-scroll chapters / transcripts when in view. Disable when out of view.

### ISSUE THREAD

**Issue by mitchdowney** [podverse/podverse-rn#1417]

**Comment by Marzal** [comment]
Hi, I think this is already implement (at least in Android), I would like to add a Feature Request due to this behavior, when I'm looking a transcript, if I'm not constantly touching the screen, my screen device will go off and then I have to activate it again, but due to the disable when out of view, I have to re-enable the auto-scroll.

Could it be an option to either have the [screen always on](https://stackoverflow.com/questions/2131948/force-screen-on) or make the "Disable when out of view" configurable?

Probably related to https://github.com/podverse/podverse-rn/issues/1838

I use to have a "Caffeine" option in my phone, but in this one I haven't found it (natively)

**Comment by mitchdowney** [comment]
@Marzal I don't think we have implemented this yet. In my tests I need to tap the auto-scroll toggle for it to begin working.

Thanks for the info. This will help inform the resolution of this issue. I wasn't aware of the auto-scroll failing on return from background.

**Comment by Marzal** [comment]
Sorry that's correct. You first have to enable auto-scroll manually, then is when if the screen goes of just for a second, when you come back, auto-scroll is off. 

Both option are complementary tough, either auto-on/off auto-scroll when in/out view and an option to prevent the screen going to sleep while watching chapters/transcripts.

**Comment by mitchdowney** [comment]
Ok cool. The auto on/off would be nice, and I think I can handle that by adding a handler when the carousel position switches  to the number of the chapters view. I think can also listen on the "app to foreground" event, and check if the carousel position equals the number of the chapters view, then either enable or disable the autoscroll.

As for preventing the screen from going to sleep...that is a pretty heavy action to take, but I can definitely see it being useful for transcripts and a lesser extent chapters. I'm not sure what "keep awake" option support is across iOS and Android versions though. It seems like something OS's don't want you to do unless it's really important.

Maybe we should split this into two separate issues, since the "moves in view" handling is easy, but the "keep awake" feature is a deeper issue?

**Comment by mitchdowney** [comment]
this should be in v4.14.2
