### ISSUE TITLE
Gary Johnson link doesn't do anything

### ISSUE THREAD

**Issue by comradekingu** [podverse/podverse-rn#1596]
**Describe the bug**
Should open a webpage, but instead lands the user back in the app.

**To Reproduce**
1. Open More → About
Click "Gary Johnson"
**Expected behavior**
Expected it to open a GitHub profile, like the others.

**Screenshots**

**Smartphone (please complete the following information):**
Latest F-Droid build

**Additional context**
[Add any other context about the problem here.
](https://github.com/podverse/podverse-rn/blob/5b01a952768f0bc0882a58a135d295b3788c6872/src/resources/Maintainers.json#L12)

**Comment by mitchdowney** [comment]
Gary doesn't want to include a link to a personal profile. He did some design work for podverse.fm which is why the link directs there, to demonstrate his work. It sucks that if we remove the link to the home page then his name will appear white while all the others appear blue. Either it's potentially seen as a bug that his name is blue and directs to podverse.fm, or it's seen as a bug that his personal link is missing. I don't have a strong opinion on how to handle it.

**Comment by mitchdowney** [comment]
This will be fixed in v4.12.4
