### ISSUE TITLE
Show urls in Chapters

### ISSUE THREAD

**Issue by beglitched** [podverse/podverse-rn#1677]
I would like to see urls in Chapters. There are a few apps that show the urls that I include when creating chapters with Podcast Chapters app.

Castamatic, Hypercatcher, and Fountain show these links. Example here. https://fountain.fm/episode/12840016226

Thanks for making the best Podcast app out there!

**Comment by mitchdowney** [comment]
@beglitched while I don't think we want to display the URLs in the player (just because there is so much information and many buttons already), as per @agates suggestion we're going to show the chapter URLs when the listener presses the chapter link button, in the "are you sure you want to leave the app?" alert modal.

**Comment by mitchdowney** [comment]
@beglitched I'm going to close this issue as a duplicate (even though it is actually the original issue) and add this feature with #1827.

Also, this should be really easy to add. I'll try to get it in the next release.
