### ISSUE TITLE
Is there a way to download episodes directly from the app, not via a third-party external server?

### ISSUE THREAD

**Issue by eta-orionis** [podverse/podverse-rn#1725]
Using Podverse on latest iOS. The podcast is hosted in a local intranet and is supposed to only be accessible within that intranet.

Adding the RSS feed works fine and the episodes get listed correctly. When clicking on the download button for any episode, however, nothing gets downloaded and the download history shows an error. After investigating server logs, I noticed the HTTP requests for the audio files do not come directly from the app. They get routed via an external DigitalOcean IP, but this IP of course cannot reach the internal intranet.

Is there a way to download the audio files directly from the app, without routing requests via external parties?

(IMHO this should be possible at least for RSS feeds that are added manually to the app, as they have a high chance of being "private" - otherwise they would not need to be added manually in the first place. Username/Password auth is not a solution, because it would still involve a third-party external server. This would add lots of work for maintaining a punched firewall, plus GDPR data protection means any third parties would need to provide and maintain a signed DPA agreement, adding even more work.

**Comment by mitchdowney** [comment]
Hi @eta-orionis this is a use case that we never anticipated. Basically what you are seeing is that the app tries to avoid `http` protocol as much as possible, and use https instead, because device and OS security settings can prevent http requests from working at all.

Given that your URLs are http, it follows the "insecure URL" path of our downloader logic, and attempts to find a secure https URL for the path by making a request to our API. The reason why our server is involved at all in this case is because if the app is unable to make an http request due to device OS settings, then we can't even ping for an https redirect URL to the http version.

Hope that makes sense. If you're able to figure out any simple fixes I'd be glad to review a PR. Here is a link to the `downloadEpisode` function and specifically the line where this "ask the Podverse server if an https version of the url is available" logic is: https://github.com/podverse/podverse-rn/blob/develop/src/lib/downloader.ts#L162

**Comment by suorcd** [comment]
@mitchdowney would adding a signed cert to the server and setting the port to 443 work?
I know that it should be possible to add your own cert to the ios device is possible as well if something like let's encrypt can't work with a DNS validation.

**Comment by mitchdowney** [comment]
@suorcd tbh I have no idea 🙈 sorry. If someone can help me understand what's needed, I could add the mobile app logic for it.

**Comment by eta-orionis** [comment]
I am sorry to have been unclear; I meant the HTTP protocol, not the http:// scheme, which nobody should be using in this day and age :)

Thanks to your hint I found where the problem was. My RSS feed was served via https://, but a misconfigured feed generator was rewriting the enclosure links inside the feed to "http". Podverse was/is working all the time as intended.

Thanks again!
