### ISSUE TITLE
add link tag information to podcasts and episodes

### ISSUE THREAD

**Issue by Ectropian** [podverse/podverse-rn#1739]
**Is your feature request related to a problem? Please describe.**
When using Podverse, especially for new users, finding commonality or community support such as "show notes" or sister podcasts within the same community, this seems to be a black hole.

MitchD: we don't render the link tag on the website yet though...that could be a Github issue feature request
MitchD: we could put a home icon in that row of icons, and have it go to whatever the podcaster sets as the link tag

**Describe the solution you'd like**
Adding an external backlink to the podcasts originality especially outside of the About field.  This could be to a Youtube channel, production website, or github page, "Home" button.

**Describe alternatives you've considered**
Copy/Paste podcast title into google to find its origination.

**Additional context**
I'd suggest using the podcasts thumbnail as the link here back to their original content.
![Screenshot 2023-03-24 at 3 21 10 PM](https://user-images.githubusercontent.com/40532636/227621475-b5589684-7aee-424d-8713-231983861d67.png)

Please feel free to [join our Matrix space](https://matrix.to/#/#podverse-space:matrix.org) and chat with us in the #dev channel if you'd like to work on this.

**Comment by mitchdowney** [comment]
This should be in v4.12.9.

There isn't a lot of real estate available for a button for this...so I kind of put it in awkwardly. Also, I originally had a 🏠 icon for this button, but talked to @kreonjr and he recommended a 🌎 icon instead. I think it's better than a home icon, because people are more likely to misinterpret that as something else.

https://github.com/podverse/podverse-rn/pull/1778
