### ISSUE TITLE
Forward (30s) and Backward (10s) Skip does not Work via Bluetooth Anymore

### ISSUE THREAD

**Issue by mitchdowney** [podverse/podverse-rn#1758]
I am using 

> 4.12.7 Build 5188 

on 

> Android 13, One UI 5.1 

running on phone

> SM-G990E/DS (Samsung Galaxy S21 FE 5G)

with bluetooth devices

> Shokz OpenRun, Jabra Elite 85t, Bose Quiet Comfort 35 and Mercedes-Benz Auto BT

For some time now (I cannot recall what version that started), I cannot use the skip forward-backward (i.e. by double/triple taps). The gesture is recognized by the bluetooth device but it is ineffective.

The same operation via the app itself or the notification banner works. 

I have a general suspicion that this started after the playback code was rewritten. Cannot be sure though.

**Comment by al3xisxyz** [comment]
Same for me, also on Android with the Nothing Stick headphones.
But the same headphones work fine on an iPhone to skip back and forward.

**Comment by mitchdowney** [comment]
I am unfortunately totally at a loss for how to fix this issue because:

1) all the bluetooth buttons are working with Podverse for all the headphones I own, so I can't reproduce the issue for debugging purposes.
2) I'm not a good Android developer, and I have no clue what is going wrong.

This is a really awful bug, but sorry all...I'm at a loss for how to proceed. I'm going to unassign myself and mark this as "help wanted".

**Comment by XceptN** [comment]
@mitchdowney this is actually the same problem described in Issue [#1794](https://github.com/podverse/podverse-rn/issues/1794)

**Comment by XceptN** [comment]
To provide a better description; The with Bluetooth, app behaves as if "Skip-track buttons jump time on headsets and the lockscreen" are _disabled_.

**Comment by RonV42** [comment]
I want to update the group.  I moved to a new Android phone from the REVVL 5G from T-Mobile which was running Android 11 to a Google Pixel 7 Pro running Android 13 and this issue still happens.  I would theorize that there is a library that is needed to make this work with Bluetooth headsets on Android.  I also paired it with Android Auto which uses the "screen" buttons and that seems to work.  But when paired with the car though Bluetooth the skip forward and backwards doesn't work. 

I have toggled the "Skip-track buttons..." multiple times to test and still the same outcome. The version from the store was 4.13.5 Build 5207

**Comment by lovegaoshi** [comment]
after initial investigation I found this is related to Event.RemoteNext and Event.RemotePrevious no longer emits when capability.Next and Prev were set as notification capabilities. Because podverse is currently stuck on RNTP v4rc04 I will just fiddle with my fork that podverse uses for a bit.

**Comment by lovegaoshi** [comment]
issue is noted in https://github.com/androidx/media/issues/216#issuecomment-1353728338
the root of this problem is skip next and skip previous are seen as queue navigation commands, which are enabled in exoplayer2 via MediaSessionConnector.QueueNavigator. not providing a capability in notification disables the queue ability all together and also skip next and previous commands.
however there is a catch: as soon as the queue capabilities are enabled, the next/prev buttons are added. these go right next to the play buttons and won't move.
while theres a solution to hide buttons in media3, copy-pasting the forwardplayer setting to RNTP (exoplayer2) doesnt work. RNTP's media3 migration could be soon, could be another couple of months. I think our solution is limited to enabling the next/prev buttons, the notification buttons dont take a styles.xml setting so they are NOT going away. I'm using andrdoid 13 so replacing icons wont budge either.
Or, we can all try to push RNTP migrating to media3. wish I did that before the AA work though:(

**Comment by lovegaoshi** [comment]
On a second thought ii can do an ugly hack writing pv a customized Bluetooth handler.  However by not having remoteskipnext, eg now is car next button on the driving wheel working for podverse android 13? Or is car also using Bluetooth control?
I might look over this more closely later

**Comment by lovegaoshi** [comment]
turns out i just need to override the onMediaButtonEvent function in kotlinaudio. submitting the fix now.

**Comment by mitchdowney** [comment]
@lovegaoshi hmm I didn't expect this to be auto-closed. I have a process of applying "ready for deploy" label to issues, so I remember to include the feature in the release notes. Anyway, I'll just keep an eye for this "auto-close" behavior through my Github notifications.

**Comment by mitchdowney** [comment]
This should be in v4.14.2. I'll close the issue, but we can reopen it if the issue persists in 4.14.2.
