### ISSUE TITLE
Importing OPML file from Stitcher Does Nothing

### ISSUE THREAD

**Issue by mitchdowney** [podverse/podverse-rn#1841]
Issue created by @landry314 in the [podverse-fdroid](https://github.com/podverse/podverse-fdroid/issues/136) repo.

> Just nothing happens when I import the OPML file I just exported from the dying Stitcher app.
> I don't know... do I need an account logged in? I am able to manually subscribe to podcasts without one.

**Comment by mitchdowney** [comment]
@landry314 the OPML import should work whether you are logged in or not. If there is not too personal of info in there, could you share the OPML file with us? Different apps have sometimes different OPML implementations, and there could be something quirky about Stitcher's that we're not setup to handle yet.

Also, which mobile OS are you using, and which version of Podverse for F-Droid? The latest available is v4.13.0.

**Comment by landry314** [comment]
LineageOS 20 (Android 13). I just downloaded it from F-Droid so the latest version, 4.13.

**Comment by Marzal** [comment]
In case you need more files to test (same problem here).

From AntennaPod beta to podverse F-Droid.

[antennapod-feeds-2023-07-26.tar.gz](https://github.com/podverse/podverse-rn/files/12176730/antennapod-feeds-2023-07-26.tar.gz)

**Comment by mitchdowney** [comment]
hey @Marzal I just tried reproducing issue using the Import OPML function with the following conditions:

1) iOS Simulator as a logged-out user
2) Android 13 (Pixel 4a) Google as a logged-out user
3) Android 13 F-Droid as a logged-out user
4) Android 13 F-Droid as a logged-in user

For 1-3 I never reproduced the issue. For 4, I reproduced the issue the first time, but then after deleting and reinstalling, I didn't run into it the next time.

Each RSS feed seems to have try / catch handling, so if one RSS feed I don't think the whole thing should fail. However, your feed has ~161 podcasts, so I wonder if the bug you ran into just has to do with how long it took to sync that many podcasts to our server or locally. Maybe there is a timeout that needs to be increased during the OPML Import requests? Unfortunately the root cause is still a mystery to me.

**Comment by mitchdowney** [comment]
I also tried reproducing the error with the Stitcher OPML that was provided by the original bug reporter, but I could not reproduce the issue. I tested these conditions:

1) Android 13 (Pixel 4a) F-Droid 4.13.2, with a logged-out user, and it succeeded2) Android 13 (Pixel 4a) F-Droid 4.13.2, with a logged-in user, and it succeeded

I asked the bug reporter if it is possible that they had some internet network condition issues when you tried importing. And also if they hadn't re-tried already, it would be helpful to know if the issue happens every time you try to import the OPML file, or if it only happened that first time.

**Comment by Marzal** [comment]
This morning I tried again F-Droid (4.13.1), same result, rebooted the phone, updated to F-Droid 4.13.2, then I started recording a video to show the process, exported from AntennaPod (3.1.0-beta3 ca9358234), imported the new OPML and this time it worked. I had to stop recording the video because it was taking too long (8 min) to import. But the thing is that now with a new OPML and 4.13.2 the problem is fixed. The process is so long that it could be a connectivity problem or timeouts. I have deleted the app data and now even the old OPML works, [stitcher.txt](https://github.com/podverse/podverse-rn/files/11941795/stitcher.txt) from [landry314](https://github.com/landry314) works too.

Also, doing some testing I found that if you try to import a file that is not an OPML, there is no error message, and that may confuse some users (in case they selected the wrong file) because the app just gets back to the "more" section and they may think that there is a problem importing, when it just the wrong file.

Thanks for your time, and sorry for the trouble.

PD: Great support of Podcasting 2.0

**Comment by mitchdowney** [comment]
Thanks @Marzal. That's a good theory that people may be getting confused by the lack of an error message when an invalid file type is selected. I just created #1881 to address that.

I also created #1882 as there definitely should be ways we can speed up the import process. I think it's highly inefficient now and we should improve this especially since it could be related to import failures.

I'm thinking of closing this issue, as it's not really clear what work is needed other than those 2 issues. If anyone thinks this should be reopened let me know.
