### ISSUE TITLE
Transcript no line wrap. long lines are off screen

### ISSUE THREAD

**Issue by takov751** [podverse/podverse-rn#1914]
**Describe the bug**
Transcript section, if line too long it will go off screen 

**To Reproduce**
Open podcast with transcript my sample was [Jupiterbroadcasting Office hours](https://podverse.fm/episode/BoH3snlmj)

**Expected behavior**
Line wrap should be implemented in transcipt section.
**Screenshots**

 ![image](https://github.com/podverse/podverse-rn/assets/40316768/6f18acd9-7194-4212-a942-1e7687c3fdb9)

**Smartphone (please complete the following information):**
 - Device: iphone11
 - OS: iOS 16.6
 - App Version 4.13.6

**Additional information**

I would like to thanks all the contributers as the app is my next favourite after AntennaPod

**Comment by mitchdowney** [comment]
@takov751 thanks for the bug report. This is a very valid one...and yet I have no idea how we can resolve this. I'm going to try to explain our technical challenges here in case someone has ideas for how to fix it.

In order to populate a mobile app view with a huge amount of content (like a full text transcript), we need to use a virtualized list, which holds the full transcript data, but *only renders X amount of list rows that are currently within the screen*.

For example, if a transcript contains 10,000 lines, the virtualized list may only render about 30 of them at a time. As you scroll, the data that appears in those 30 rows will change, but there will still only ever be 30 rows rendered at a time. This is needed for performance / efficiency reasons.

The problem is...in order for a virtualized list to work, you must have consistently sized rows. If a single line of text is 24 pixels tall, and a single line of *word wrapped* text (2 lines of text) is 48 pixels tall, then our virtualized list needs to know if that line will be word wrapped or not (aka if the row should be 24 or 48 pixels tall) *before* loading the data in the list.

Given that font sizes may not be equal across different devices (especially have increased font size turned on their phone), I have no idea how we can reliably predict how many text characters will fit horizontally at a time on any given screen...without that information, I can't tell the virtualized list how to vertically size each row of text.

Maybe there is an entirely different approach to rendering transcripts on screen than a virtualized list, but I'm not aware of it. I also don't want to dramatically change our current design/layout pattern for rendering transcripts, but if people have alternate design ideas I'd consider them.

**Comment by takov751** [comment]
Puzzling indeed, I am no expert nevertheless i will ponder over it

**Comment by mitchdowney** [comment]
This should be improved in v4.14.3.

![CleanShot 2023-10-31 at 16 13 43](https://github.com/podverse/podverse-rn/assets/2262919/4497efc1-4b6d-4a0b-9820-7c96a67d4b4f)

more discussion: https://podcastindex.social/@mitch/111331720887223242
