### ISSUE TITLE
App starts empty

### ISSUE THREAD

**Issue by omazeas** [podverse/podverse-rn#1941]
Hi,
All of a sudden, opening the app, I get everything empty. (It starts on "followed podcasts").
No podcast subscription, nothing downloaded. 
When I get to " all the podcasts", I do have the most popular podcasts and everything. So it is not dead at all. Just nothing I configured shows up. The configuration seems to be kept though since it starts with the option "followed podcasts".
Version 4.13.8. I don't have an account so no explanation by possibly not signing-in...
I am on android 12 (not the google one) under fairphone 3 with e/os 1.14. Everything up-to-date. 
Restarting the phone does not change anything. My phone tells me the app has 6Go of data on the drive...
Is there any fix to try for this kind of... Bug or accident?

**Comment by mitchdowney** [comment]
Hi @omazeas, I'm very sorry for the trouble. It sounds like for some reason the app has lost track of the path to where your podcast subscription data is saved locally on your device...did you by chance recently update your device's OS version? Or make any possibly related device settings changes?

One of the challenges for us here is that we haven't tested Podverse using a Fairphone or e/os before, so we can't guarantee app support for it right now.

Are you familiar with Android Studio by chance? If not, feel free to skip this paragraph...could you connect your device to your computer, run Android Studio, and search the Logcat panel for "podverse" and see if any errors jump out to you? I'm not sure how else we will get the error information from your device, since we don't have tracking or error reports on the F-Droid version.

Another question, do you have many Add by RSS feeds by chance? There is a known issue with [storage limits](https://github.com/podverse/podverse-rn/issues/1611) on Android that we have not resolved yet, but it only seems to surface for people who have many Add by RSS feeds. Once the storage limit is exceeded, the app can no longer read from storage. If this is indeed the bug you're running into, then unfortunately the only way I know of to fix it would be to delete and reinstall the app, and not add so many Add by RSS feeds.

But it's possible it's a different issue entirely...sorry I don't have a simple answer for you at this time. If you would like a free Premium membership, which could at least back your feeds up to our server so you shouldn't have to re-add your podcasts again, please email us at contact@podverse.fm, but I understand that may not be useful for you if the app itself just won't work on your device.

**Comment by omazeas** [comment]
Thanks for jour detailed reply Mitch.
I have updated the operating system about 1 week ago but use podverse everyday since and many times a day. And the problem appeared during a day with no change that I know of just before...
Just to better understand : AsyncStorage is a system file, not a podverse file?
I don't know its size but I may have had between 30-40 feeds. I don't think it's crazy...
I will give Android studio a try. I was using something similar to help fix bugs with e/os.
For the premium account, podverse still works on my phone but starting from zero. Will the premium access allow me to recover my previous config and file path or will I have to re-enter my feeds and loose my downloaded files ?

**Comment by mitchdowney** [comment]
@omazeas unfortunately, if the bug is with the storage getting filled, you will likely lose the _downloaded_ files 😔 using Premium would just save your podcast subscription list, and listening history (amongst potentially other things).

Did you subscribe to all 30-40 feeds using the Podverse search feature? If yes, then those are not the custom "Add by RSS" feeds (aka manually added by RSS feed url), and in that case, subscribing to 40 feeds should not be a problem. The "Add by RSS" feeds use AsyncStorage, which I believe is a Sqlite database underneath the hood, and Android enforces about a 10MB limit on that database...I didn't realize this limitation existed until we already implemented it with AsyncStorage.

Maybe you used the Import OPML feature when you first used the app? If yes, then some or many of those feeds may be "Add by RSS" feeds that were not found through our search engine, and that could explain how/if the storage limit got reached.

The big problem if the storage limit got reached is that all requests to the Sqlite database fail, even simple "get from storage" function calls, making the app unusable...

If you did update the OS recently, and the Podverse issue appeared recently, it's not impossible that something about the OS update broke the previous file path the app used for saving your data locally. If the upgrade caused it, then a Premium membership actually may have made recovering from this problem smoother, as you could have restored your subscriptions from our servers. I don't want to blame the upgrade for the error because I don't honestly know, but e/os is definitely uncharted territory for us in terms of what we official support and test for.

So again unfortunately it's not looking good for easily restoring your previous app state...for what it's worth, I just created [this Github issue](https://github.com/podverse/podverse-rn/issues/1944) for the work needed that would prevent people from running into the storage limitation bug going forward, and assigned it to me.
