### ISSUE TITLE
Streaming sats does not update when episode changes

### ISSUE THREAD

**Issue by stevencrader** [podverse/podverse-rn#1976]
**Describe the bug**
I've seen the stream sats settings not update in a couple of use cases.

The first was switching from the Boostagram Ball live stream to a recorded Podcasting 2.0. The sats info didn't update and kept sending sats to the Boostagram Ball value blocks. I'm not sure what version of the app I was using during this time. I noticed it on September 1, 2023 if that helps narrow the version.

The second was seen today while running Android app version 4.14.0 Build 5218 while using the Android Auto interface. When the phone connected, it started playing the latest Podcasting 2.0 episode. Since I had already listened to it, I selected the latest Megyn Kelly show episode and started listening to it. For Podcasting 2.0, I was streaming at 100 sats/min. The Megyn Kelly show does not support v4v so streaming should have stopped. 

When I got home and opened the Podverse app, I noticed the UI still showed it was streaming sats. Upon review of my Alby account, it continued to stream sats to the Podcasting 2.0 value blocks while I was listening to the Megyn Kelly show.

**To Reproduce**
I've been unable to reproduce either behavior. I'll keep trying and will update this issue if I find a way to reproduce it.

**Expected behavior**
When starting a new episode or live stream, the stream sats should update to the new value blocks or stop if not supported by the new episode.

**Screenshots**
Here is a screenshot I have from the first issue. Notice the block data is for Boostagram Ball and not Podcasting 2.0. At that time, I don't believe there should have been any remote value blocks but they were being used too.
<img src="https://github.com/podverse/podverse-rn/assets/677342/1ab2a6e7-016d-4452-ad2c-670ab14e8bb1" width="200" />

Here is a screenshot of the sats being streamed while listening to the Megyn Kelly show.
<img src="https://github.com/podverse/podverse-rn/assets/677342/8fa9b2bb-e163-487b-99c5-82b9eac90a01" width="200" />

Here is one of the Alby transactions
<img src="https://github.com/podverse/podverse-rn/assets/677342/9ab452a1-537d-426c-84dc-0aac9af4b70c" width="500" />

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S22 Ultra 5G
 - OS: Android 13
 - App Version: 4.14.0 Build 5218

**Comment by mitchdowney** [comment]
@stevencrader hmm I wonder if this is related to our Android Auto implementation then? Perhaps after an episode changes in Android Auto, the boost / streaming buttons are not updating properly? Do you know if you've seen this issue at times where Android Auto wasn't involved?

**Comment by stevencrader** [comment]
@mitchdowney the first issue with Boostagram Ball and Podcasting 2.0 was before Android Auto. This second version was only with Android Auto.

I tried to reproduce again once I got home but was unable to.

**Comment by lovegaoshi** [comment]
AA uses the same playback handlers as carplay, shouldnt be anything specific in the AA implementation itself:S

**Comment by mitchdowney** [comment]
@stevencrader do you know if both of these issues either happened while listening to a livestream, or directly after listening to a livestream?

I think there may be a problem with a race-condition in the `v4vEnrichValueTagDataIfNeeded` function. When a new item loads in the player, this `v4vEnrichValueTagDataIfNeeded` function runs once...but it takes time to complete the network requests to our API to stitch together all the remoteItem valueTags, and I think if `v4vEnrichValueTagDataIfNeeded` doesn't complete before the new item is in the player, then an `episodeValue` property will be assigned to the `nowPlayingItem`, and the boost buttons will display with the previous nowPlayingItem's valueTag info 😓

One thing I think we can do to avoid this problem is ensure the `v4vEnrichValueTagDataIfNeeded` does not run at all when the `nowPlayingItem` is not a liveItem (doesn't have `nowPlayingItem.liveItem` as a property).

Another thing that might help, maybe, is before the `v4vEnrichValueTagDataIfNeeded` updates the global React state with the retrieved remoteItem valueTags, to confirm that the nowPlayingItem the enriching happened for is still the same nowPlayingItem when we assign the remoteItem value tags to the nowPlayingItem.

If this fix can work then at best it seems messy and far from ideal...but I'm not sure I can come up with a realistic solution without an entire rewrite of the mobile app, with all the new Podcasting 2.0 features taken into consideration from the ground up. There are so many use cases I never anticipated we would support as a podcast app (especially livestreams, value tags, and remote value time splits).

**Comment by mitchdowney** [comment]
A fix for this should be in v4.14.3. @stevencrader if you see the issue again after installing v4.14.3, please let us know.

**Comment by stevencrader** [comment]
I think the second case ws from a Podcasting 2.0 episode (not live) and then the Megyn Kelly show. 
I haven't seen the issue since I wrote the issue.
