### ISSUE TITLE
Android Auto episode changes between list and grid view

### ISSUE THREAD

**Issue by stevencrader** [podverse/podverse-rn#1977]
**Describe the bug**
I have my Podverse app set to use the Grid View. I've noticed that if Podvers isn't already running and Android Auto launches it, the episodes are shown in a List View. If Podverse is already running and Android Auto is connected, it seems to follow my setting of Grid View.

**To Reproduce**
1. Configure episode page for grid view
2. Connect phone to Android Auto
3. Open Podverse on the head unit
4. Notice the episodes are shown in a Grid View
5. Disconnect the phone from Android auto
6. Close the Podverse app on the phone (open recents and swipe it away)
7. Connect phone to Android Auto
8. Open Podverse on the head unit
9. Notice the episodes are shown in List View

**Expected behavior**
I don't care what view is used in Android Auto but I would expect the same view to be used regardless of open method.

**Screenshots**
Here are screenshots from the head unit showing the 2 different views.

![grid_view](https://github.com/podverse/podverse-rn/assets/677342/5f73185b-ad1f-40ab-b0ab-84bbbeab9de3)
![list_view](https://github.com/podverse/podverse-rn/assets/677342/72e91160-4e15-4444-9a91-e0ce20b146ba)

**Smartphone (please complete the following information):**

- Device: Samsung Galaxy S22 Ultra 5G
- OS: Android 13
- App Version: 4.14.0 Build 5218

**Comment by lovegaoshi** [comment]
this is an interesting issue...
the style definition is at 
https://github.com/podverse/podverse-rn/blob/c7c932bac480a7980a77b98ef58b1d12e01a4b1b/src/lib/carplay/PVCarPlay.android.ts#L199
the default style is list, I made it grid because I thought it looked better. So it behaving as list is due to this above didnt work. I know once the contents were accessed, the style can no longer be changed, so there seems to be a race condition here.
we might want to port
https://github.com/lovegaoshi/react-native-track-player/commit/bf538bacb842e93d05749a1bd5786e53d69ca970
and just set style in each podcast item, instead of a global style.
alteratively we can just use list and call it a day

**Comment by mitchdowney** [comment]
@lovegaoshi if it is even somewhat difficult to make this work with 2 different views and/or grid view, I am fine with just supporting list view. Grid view could be a future enhancement.

**Comment by lovegaoshi** [comment]
@mitchdowney so you also think the grid view looks better;) shouldnt be a difficult fix, i might try this week
