### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [podverse/podverse-rn#2035]
...as the final APK has no versionCode

```
$ aapt2 dump badging app-x86_64-release-unsigned.apk|head
package: name='com.podverse.fdroid' versionCode='' versionName='4.14.3' platformBuildVersionName='' platformBuildVersionCode='' compileSdkVersion='33' compileSdkVersionCodename='13'
sdkVersion:'23'
targetSdkVersion:'33'
```

Looking at the recipe, we calculate the per ABI version code like so: https://gitlab.com/fdroid/fdroiddata/-/commit/4cbb4f43e2cf063a0cbfd62e5fd7469f6b3b721f#6472a6ad9324e8dd9a38e0bfc4fdd17e7d5e7bf4_6531_6731

since you'[ve gone](https://github.com/podverse/podverse-fdroid/commit/bde37bc40da6d565645d04aaf49fe15fd0690017#diff-9526ccfd1d1813ed49c39f8c54dbeb512607376a007d824b905bc8b4e4d202d9R138) from `96` to `1699334518`  maybe we're overflowing the final versionCode type?

ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/5496750646#L4108

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/bef6d67c408e04e2243ab4f8d0bf07ea46d6598f

**Comment by licaon-kter** [comment]
`Note: The greatest value Google Play allows for versionCode is 2100000000.`

https://developer.android.com/studio/publish/versioning.html#versioningsettings

So you've already touched upper limits and F-Droid can't multiply anything... :cry:

**Comment by mitchdowney** [comment]
@licaon-kter doh! I intended to only use epoch time as versionCode for our self-hosted Beta distribution...after talking in the F-Droid Matrix room, this was the only option that seemed to make sense for our purposes...but i suppose i could just start our beta track at something like 10000 since we are changing it back to 95, 96, 97 etc in our prod track. Including screenshots of the convo for posterity.

I just force updated the 4.14.3 tag in the Podverse F-Droid so the versionCode in the build.gradle matches the com.podverse.fdroid.yml file. Could that fix the issue? https://github.com/podverse/podverse-fdroid/commit/2f5b418ee530bc9b1d0be6ca6f1cbb5008abcff8

![image](https://github.com/podverse/podverse-rn/assets/2262919/70bb6437-5420-4158-b1a8-7837d9f9f648)

![image](https://github.com/podverse/podverse-rn/assets/2262919/84867736-4f45-4837-b6ed-1dfc88361e3c)

**Comment by licaon-kter** [comment]
Thanks https://gitlab.com/fdroid/fdroiddata/-/commit/6ac7738ea09d8215fff1e2011a185baaa44de944
