### ISSUE TITLE
Subscribe to podcast from "Episodes"

### ISSUE THREAD

**Issue by comradekingu** [podverse/podverse-rn#828]
Browsing the popular entries in "Episodes" requires clicking "Go to Podcast" from the "…" menu.
After clicking the "Subscribe" the only option is to click ←, which lands at "Podcasts".
I suppose some part of the issue is ← should really go back to the previous screen.
When clicking Episodes again, it is scrolled to the top, so it is (more) difficult to collect podcasts this way.

Solution,  "…" clicked from the Episodes list, or when clicking the episode should have a "Subscribe".

**Comment by mitchdowney** [comment]
@comradekingu I'm thinking of not adding a "Subscribe to podcast" button to the Episodes screen only because there are already 10 buttons that appear when you press the "More" button in Episode table cells. Yes it is not the most convenient to have to press "Go to Podcast" to press the subscribe button, but I so rarely need/want to subscribe to a podcast from the EpisodesScreen that I don't think we should add an 11th button for it. I'm still open to an easier subscription path, but I'm going to close the issue for now and will reopen if we decide to work on it later.
