### ISSUE TITLE
Feature request: a list of episodes that have been started but not finished

### ISSUE THREAD

**Issue by Chris869218** [podverse/podverse-rn#871]
**Is your feature request related to a problem? Please describe.**
If I start listening to an episode that I haven't already added to a playlist, it can be difficult to find it again to finish listening. 

**Describe the solution you'd like**
A number of options would solve this: 
- An amount remaining indictor on the 'History' screen
- A default playlist that is comprised of all episodes that have been started but not finished
- On the 'Podcasts' tab, have a filter for 'unfinished' in addition fo 'Subscribed', 'Downloaded, 'All Podcasts', and 'Category'
- On the 'Podcasts' tab, have a 'Sort' for 'time remaining' 

Thanks!

**Comment by mitchdowney** [comment]
I can definitely see this being useful. It's a fairly large amount of work though, and I'm not sure when we'll have the resources for it.

There is a feature that might be somewhat related to what you're looking for in v4.1.0. Settings > Queue > "Add current item next in queue when playing a new item". With that enabled you should be able to keep unfinished episodes in your queue (unless it's not working properly).

**Comment by Chris869218** [comment]
Thanks a lot, was not aware of "Add current item next in queue when playing a new item," that definitely helps. Is there a reason that setting doesn't start toggled on by default?

**Comment by mitchdowney** [comment]
@Chris869218 the reason it's not on by default is it seemed like it can get confusing for some users what exactly is will be next in their queue...I found myself getting tripped up with it, and thought of adding it as an advanced feature.

Since we have a "Hide completed episodes by default" feature now in More > Settings > Other, I'm thinking of closing this issue as "won't do". The UI gets at risk of being too cluttered if we put every possible feature in. I'd like to say "Add current item next in queue when playing a new item" helps keep unfinished episodes in your queue so a filter is unnecessary. Anyway, if there is more demand for this feature we can reopen it.
