### ISSUE TITLE
Web version Clip screen not filling in the start or end times and no button to push

### ISSUE THREAD

**Issue by brianoflondon** [podverse/podverse-rn#880]
**Describe the bug**
When trying to clip, the start time when you press the clip icon doesn't show up and there doesn't seem to be a way to get them filled in like on the iOS version.

 - Device: Mac Web
 - Browser: Brave

Please feel free to [join our Discord](https://discord.gg/6HkyNKR) and chat with us in the #dev channel if you'd like to work on this.

**Comment by mitchdowney** [comment]
Since podverse-web is the repo for the website (desktop and mobile), I created a ticket in podverse-web for the Start Time feature.

As for the "tap to set the current time as the start or end time" feature...I'm not sure if we want to have that UX on mobile web? The progress bar experience is generally smoother in the mobile app, but the progress bar touch event handling in the web app will be clunkier.

@kreonjr any thoughts on this? I guess we could add a "Set" button next to the start/end clip times, that on press takes whatever the current playback position and sets it to the input...but I'm not sure if the form is too cluttered then.

**Comment by mitchdowney** [comment]
@brianoflondon are there still things you want improved with the Podverse mobile or web UX?

**Comment by mitchdowney** [comment]
@brianoflondon I'm closing this issue since it seems focused on podverse-web. If you'd like improvements added to the mobile clip maker, please open another issue.
