### ISSUE TITLE
Allow Marking Multiple or All Episodes as Played (bulk mark as played)

### ISSUE THREAD

**Issue by KyleFDowney** [podverse/podverse-rn#935]
When marking an episode as played, currently only one episode can be edited at a time.

Implementing a bulk edit feature would greatly speed up the process.

**Comment by mitchdowney** [comment]
This is easily one of our most popular feature requests. It's one of the first things that new listeners want when they switch to Podverse.

Since our core dev team hasn't had time to work on this in over 2 years, I went ahead and created a bounty so we can pay an open source contributor if they're up for completing the work.

We haven't totally ironed out / written out the details of the bounty program, but if you'd like to pick this up, let me know and we could explain terms and see if we can reach an agreement.

https://github.com/podverse/podverse-ops/blob/master/bounties/mobile-react-native/mark-multiple-or-all-episodes-as-played.md

**Comment by mitchdowney** [comment]
This will be in v4.13.8.
