### ISSUE TITLE
Feature request: Support skipping audio ads with SponsorBlock

### ISSUE THREAD

**Issue by williamtheaker** [podverse/podverse-rn#938]
Audio ads in podcasts are getting more pervasive and bothersome. [SponsorBlock](https://sponsor.ajay.app/) is a crowd-sourced database of sponsor segment timestamps in YouTube videos. The lead developer of SponsorBlock has already [expressed interest in adding support for podcasts](https://github.com/AntennaPod/AntennaPod/issues/4159#issuecomment-645084915) and has chimed in on this [Antennapod discussion thread](https://forum.antennapod.org/t/ability-to-skip-ads-in-the-podcast/212).

Implementing optional support for skipping certain segment types, like requests for sponsorship or rating the podcast, advertisements, or musical intros would save users time, especially those who are already skipping through these segments.

**Comment by mitchdowney** [comment]
Ohh very interesting...I have to discuss this with the other co-founders, but I'm not on principle opposed to integrating an "ad skipping" service into Podverse. It would be an advanced feature if it's included at all.

That said, @kreonjr and myself have sooo many features and bug fixes to work on, I don't expect us to have time to prioritize adding a feature that is not only an advanced setting, but a feature that will likely piss off some podcasters. If people in the open source community code this integration for Podverse I'm not opposed to allowing it as a feature, but I doubt it will be a top priority for Creon and I in the near-term at least.

For now though, it seems SponsorBlock is not even ready to integrate with podcast apps? If that's true, I'd recommend closing this issue until SponsorBlock is ready to be added to podcast apps, since there's no path forward for us until then.

**Comment by mitchdowney** [comment]
@williamtheaker as far as I know, there has been no progress on SponsorBlock enabling skipping audio in podcasts...since there is nothing we can do until SponsorBlock offers this functionality, I'm going to close this ticket for now. If I'm wrong and SponsorBlock actually does support skipping podcasts, then we can reopen it.
