### ISSUE TITLE
Play Store Data Safety Section

### ISSUE THREAD

**Issue by vaibhavantil1** [podverse/podverse-rn#939]
Hi Team

In the recent Play Store policy, it will become mandatory for you to fill out the Data Safety Section. Since this is an OSS Android app, it will make sense to have it as a part of the repository as well.

I have run the scan using [my tool here](https://github.com/Privado-Inc/privado) on your repo, attached are the scan results. I found the following:

- 4 data types
- 1 SDK

If this is helpful, do use our free tool to generate Play Store Data Safety report: https://github.com/Privado-Inc/privado

Also, do share your feedback & thanks for the OSS app 😄
![image](https://user-images.githubusercontent.com/87804852/157263846-da15aab5-9b1d-4170-b7f6-a79464f0d4d2.png)
![image](https://user-images.githubusercontent.com/87804852/157264087-dd154565-26b6-49ba-a6c8-2f8aa67de72f.png)

**Comment by mitchdowney** [comment]
@vaibhavantil1 thanks for scanning this for us! Privado looks really cool.

It looks like the react-native-share module is getting flagged...which I guess makes sense because Facebook and Google are involved...but if the user doesn't have Facebook or Google apps installed on their device, is there really any privacy risks involved with the react-native-share module? I would think the react-native-share module just facilitates the ability for a Podverse user in this case to choose to open Facebook/Google with a Podverse link if they want to.

I'm not sure what to do with this info at the moment... @kreonjr maybe we should review this together.

**Comment by mitchdowney** [comment]
I believe @kreonjr and I filled out the Play Store Data Safety info about a month ago.
